#!/usr/bin/expect -f

set timeout 20
set host "135.181.201.185"
set user "root"
set password "xTVvPEwrpaF4"

spawn ssh-copy-id -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "Now try logging into the machine" {
        exit 0
    }
    "already exists on the remote system" {
        exit 0
    }
    timeout {
        exit 1
    }
    eof
}
